-- differentmaptextures ModuleScript
local DMT = {
	[1] = {
		Color = Color3.fromRGB(12, 181, 0),
		Material = "Grass"
	},
	[2] = {
		Color = Color3.fromRGB(80, 80, 80),
		Material = "Concrete"
	},
	[3] = {
		Color = Color3.fromRGB(163, 162, 165),
		Material = "RoofShingles"
	},
	[4] = {
		Color = Color3.fromRGB(255, 204, 153),
		Material = "Sand"
	},
	[5] = {
		Color = Color3.fromRGB(234, 184, 146),
		Material = "Wood"
	},
	[6] = {
		Color = Color3.fromRGB(255, 255, 255),
		Material = "Snow"
	},
	[7] = {
		Color = Color3.fromRGB(215, 197, 154),
		Material = "Cardboard"
	},
	[8] = {
		Color = Color3.fromRGB(0, 229, 255),
		Material = "DiamondPlate"
	},
	[9] = {
		Color = Color3.fromRGB(91, 93, 105),
		Material = "Carpet"
	},
	[10] = {
		Color = Color3.fromRGB(126, 227, 255),
		Material = "Ice"
	},
	--[[ [11] = {
		Color = Color3.fromRGB(0, 0, 0),
		Material = "Neon"
	,]] --This genuinely sucks as a color. Bombs are invisible, it looks off, people that are full black can blend in
}

return DMT
